os:
  - linux

sudo: false

language: go

env:
    - UDFS_REUSEPORT=false

go:
    - 1.9.x

install:
  - make deps

script:
  - bash <(curl -s https://raw.githubusercontent.com/udfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
